# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_development
  pool: 5
  username: ricardo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_test
  pool: 5
  username: ricardo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: damgdasbi6grhn
  pool: 5
  username: sylxwsyjjbhrjd
  password: A873qXClcZDjfpoy5BHG9odG_M